### ISSUE TITLE
Which version of benepar are you using

### ISSUE THREAD

**Issue by cyzus** [juliaiwhite/clarification-question-generation#1]
I've set up the conda environment using "environment.yml" you provided and tried to train the response classifier. It then reported that it missed the modules of spacy and benepar. I've installed spacy and benepar respectively, but pytorch would get updated to a higher version (=1.10.2) which would cause the pre-trained image-captioning model fails to load.

Could you provide a new environment.yml that includes spacy and benepar? Thanks

**Comment by juliaiwhite** [comment]
Oops, thanks for catching that. The environment.yml file is updated!
